# -*- coding: utf-8 -*-
"""Projet-apprentissage-auto-partie1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCqrBM1zKQ1MCa9r-cG91Jc7WjS5Hl8X

# Projet - Apprentissage automatique

- [Vous êtes ici]
- [Spécial - Division des données](https://colab.research.google.com/drive/1nj8v8rWsDm34sya57gXGBetxj_wQgUb7?usp=sharing)
- [Partie 2 - ML Classique](https://colab.research.google.com/drive/1xJjvVe1jds_r-YMwUfnndlS3tUS_femc?usp=sharing)
- [Partie 3 - CNN](https://colab.research.google.com/drive/13NIe3ENacjGwOxr6ZYAuF7Xg5K_rpy2u?usp=sharing)
- [Partie 4 - BILSTM](https://colab.research.google.com/drive/1QA7sIiwOHSTdhzxJzh0D-HS1SRHa3SIm?usp=sharing)
- [Partie 5 - Transformers](https://colab.research.google.com/drive/1U-vjDYcGoGWQHiG-YZ8TWFFwi-uwp7aA?usp=sharing)
- [Partie 6 - Conclusion](https://colab.research.google.com/drive/1CInFVJpJoXfEVUUbGCXDJ4CACKKGF4N_?usp=sharing)

## Partie 1 - Analyse des données
"""

!pip install spacy
# Je prend le modèle small dans le but d'économiser des unités de calcul
!python -m spacy download fr_core_news_sm

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from collections import Counter
import spacy
import fr_core_news_sm

!wget https://git.unistra.fr/dbernhard/ftaa_data/-/raw/main/final_symptom_dataset.csv

data = pd.read_csv('final_symptom_dataset.csv')

print(data.head())
print(data.info())

"""Nous avons donc 760 exemples pour entrainer nos modèles, ce qui est relativement faible.

### Visualisation de la distribution des exemples
"""

maladie_distribution = data['label_fr'].value_counts()
plt.figure(figsize=(15, 7))
plt.pie(
    maladie_distribution,
    labels=maladie_distribution.index,
    autopct=lambda p: f'{int(round(p * maladie_distribution.sum() / 100))}',
    startangle=0
)
plt.title("Distribution des exemples")
plt.show()

"""21 classes se partagent les 760 exemples, dans une proportion pas toujours équilibrée, ce qui peut poser problèmes pour les maladies avec très peu d'exemples.

### Visualisation de la longueur des descriptions
"""

def word_count(text):
    return len(text.split())

data['count_desc'] = data['description'].apply(word_count)
data['count_simple'] = data['simple'].apply(word_count)
data['count_fautes'] = data['fautes'].apply(word_count)


plt.figure(figsize=(15, 7))
plt.boxplot([data['count_desc'], data['count_simple'], data['count_fautes']])
plt.title("Longueur des descriptions")
plt.ylabel("Mots")
plt.xticks(ticks=[1, 2, 3], labels=['Description', 'Simple', 'Fautes'])
plt.show()

"""On observe que les longueur des descriptions sont en moyenne relativement équivalentes, mais peuvent varier de 10 à 60 caractères.

### Qu'en est-il de la taille des vocabulaires ?

"""

def vectorize_column(column_name, data):
    vectorizer = CountVectorizer()
    vectorizer.fit(data[column_name])
    vocab_size = len(vectorizer.get_feature_names_out())
    return vocab_size

description_vocab_size = vectorize_column('description', data)
simple_vocab_size = vectorize_column('simple', data)
fautes_vocab_size = vectorize_column('fautes', data)

print(f"Vocabulaire Description: {description_vocab_size}")
print(f"Vocabulaire Simple: {simple_vocab_size}")
print(f"Vocabulaire fautes: {fautes_vocab_size}")

"""La réduction de taille entre "description" et "simple" semble normale, mais la taille anormale du vocabulaire des fautes pourrait s'expliquer par la variation orthographique, chaque nouvelle faute étant considérée comme un nouveau terme.

### Mots les plus utilisés de chaque vocabulaire
"""

def get_top_words(text_column, top=10):
    # Passage en lowercase pour éviter les doublons
    all_words = ' '.join(text_column).lower().split()
    # Utilisation de Counter() parce pour la simplicité
    most_common = Counter(all_words).most_common(top)
    return pd.DataFrame(most_common, columns=['Mot', 'Fréquence'])

print("\nTop mots pour Description:\n", get_top_words(data['description']))
print("\nTop mots pour Simple:\n", get_top_words(data['simple']))
print("\nTop mots pour Fautes:\n", get_top_words(data['fautes']))

"""Cela fait sens que les stop-words soient les plus représentés, il faudrait effectuer une pondération TF-IDF pour faire émerger les termes les plus important.

### Mots les plus utilisés avec pondération TF-IDF
"""

def get_top_tfidf_words(text_column, top=10):
    tfidf = TfidfVectorizer()
    tfidf_matrix = tfidf.fit_transform(text_column)

    tfidf_scores = tfidf_matrix.sum(axis=0).A1
    words = tfidf.get_feature_names_out()

    word_scores = list(zip(words, tfidf_scores))
    sorted_scores = sorted(word_scores, key=lambda x: x[1], reverse=True)

    return pd.DataFrame(sorted_scores[:top], columns=['Mot', 'Fréquence'])

print("\nTop mots (TF-IDF) pour Description:\n", get_top_tfidf_words(data['description']))
print("\nTop mots (TF-IDF) pour Simple:\n", get_top_tfidf_words(data['simple']))
print("\nTop mots (TF-IDF) pour Fautes:\n", get_top_tfidf_words(data['fautes']))

"""Les résultats ne sont pas très satifaisants, il serait judicieux d'effectuer un prétraitement du texte et de retirer les stop-words avant d'effectuer de nouvelles mesures.

### Prétraitement avec spaCy
"""

nlp = spacy.load("fr_core_news_sm")

spacy_pipeline = fr_core_news_sm.load(disable=["parser", "ner", "lemmatizer"])

def split_into_tokens_wosw_spacy(text):
    doc = spacy_pipeline(text)
    # Suppression de la ponctuation parce qu'elle n'est pas nécessaire pour la création d'un vocabulaire
    return ' '.join([t.text for t in doc if not t.is_stop and not t.is_punct])

columns = ['description', 'simple', 'fautes']
preprocessed_data = pd.DataFrame()

for i in columns:
    preprocessed_data[i] = data[i].astype(str).apply(split_into_tokens_wosw_spacy)

preprocessed_data.head()

"""Maintenant que le texte a été prétraité, nous pouvons recréer un premier vocabulaire"""

print("\nTop mots pour Description:\n", get_top_words(preprocessed_data['description']))
print("\nTop mots pour Simple:\n", get_top_words(preprocessed_data['simple']))
print("\nTop mots pour Fautes:\n", get_top_words(preprocessed_data['fautes']))

"""Et une autre version avec pondération TF-IDF"""

print("\nTop mots (TF-IDF) pour Description:\n", get_top_tfidf_words(preprocessed_data['description']))
print("\nTop mots (TF-IDF) pour Simple:\n", get_top_tfidf_words(preprocessed_data['simple']))
print("\nTop mots (TF-IDF) pour Fautes:\n", get_top_tfidf_words(preprocessed_data['fautes']))

"""### Production d'un word cloud basé sur la fréquence du nouveau vocabulaire
Un word-cloud a été créé par colonne/vocabulaire
"""

def show_wordcloud(score, title):
    from wordcloud import WordCloud
    word_freq = dict(zip(score['Mot'], score['Fréquence']))
    wordcloud = WordCloud(width=600, height=400, background_color='white').generate_from_frequencies(word_freq)
    plt.figure(figsize=(12, 6))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.title(title)
    plt.axis('off')
    plt.show()

show_wordcloud(get_top_words(preprocessed_data['description'], 50), "Description")
print("\n")
show_wordcloud(get_top_words(preprocessed_data['simple'], 50), "Simple")
print("\n")
show_wordcloud(get_top_words(preprocessed_data['fautes'], 50), "Fautes")

"""### Basé sur TF-IDF"""

show_wordcloud(get_top_tfidf_words(preprocessed_data['description'], 50), "Description")
print("\n")
show_wordcloud(get_top_tfidf_words(preprocessed_data['simple'], 50), "Simple")
print("\n")
show_wordcloud(get_top_tfidf_words(preprocessed_data['fautes'], 50), "Fautes")