# -*- coding: utf-8 -*-
"""Projet-apprentissage-auto-partie3-CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NIe3ENacjGwOxr6ZYAuF7Xg5K_rpy2u

# Projet - Apprentissage automatique

- [Partie 1 - Analyse des données](https://colab.research.google.com/drive/1TCqrBM1zKQ1MCa9r-cG91Jc7WjS5Hl8X?usp=sharing)
- [Spécial - Division des données](https://colab.research.google.com/drive/1nj8v8rWsDm34sya57gXGBetxj_wQgUb7?usp=sharing)
- [Partie 2 - ML Classique](https://colab.research.google.com/drive/1xJjvVe1jds_r-YMwUfnndlS3tUS_femc?usp=sharing)
- [Vous êtes ici]
- [Partie 4 - BILSTM](https://colab.research.google.com/drive/1QA7sIiwOHSTdhzxJzh0D-HS1SRHa3SIm?usp=sharing)
- [Partie 5 - Transformers](https://colab.research.google.com/drive/1U-vjDYcGoGWQHiG-YZ8TWFFwi-uwp7aA?usp=sharing)
- [Partie 6 - Conclusion](https://colab.research.google.com/drive/1CInFVJpJoXfEVUUbGCXDJ4CACKKGF4N_?usp=sharing)

# Partie 3 : CNN
Dans cette partie, nous évaluons les performances des CNN
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

!wget https://raw.githubusercontent.com/shael-nlp/classification-symp/refs/heads/main/data/train_data.csv
data = pd.read_csv('train_data.csv')

data_complete = pd.DataFrame({
    'text': pd.concat([data['description'], data['simple'], data['fautes']], ignore_index=True),
    'label': pd.concat([data['label_fr'], data['label_fr'], data['label_fr']], ignore_index=True)
})

label_mapping = {label: idx for idx, label in enumerate(data_complete['label'].unique())}
data_complete['label_encoded'] = data_complete['label'].map(label_mapping)

tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(data_complete['text'])
sequences = tokenizer.texts_to_sequences(data_complete['text'])

# Padding
max_length = 100
X = pad_sequences(sequences, maxlen=max_length, padding='post')
y = data_complete['label_encoded'].values

embedding_dim = 128
num_classes = len(label_mapping)

def build_model():
    """Construit le modèle CNN."""
    model = Sequential([
        Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=embedding_dim, input_length=max_length),
        Conv1D(128, 5, activation='relu'),
        GlobalMaxPooling1D(),
        Dropout(0.5),
        Dense(64, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Validation croisée
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
f1_scores = []
fold = 1

for train_idx, val_idx in kfold.split(X, y):
    print(f"\n--- Fold {fold} ---")
    X_train, X_val = X[train_idx], X[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    model = build_model()

    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=5,
        batch_size=32,
        verbose=1
    )

    y_val_pred = np.argmax(model.predict(X_val), axis=-1)
    f1 = f1_score(y_val, y_val_pred, average='macro')
    f1_scores.append(f1)

    print(f"Fold {fold} - F1 Score: {f1:.4f}")
    print(classification_report(y_val, y_val_pred, target_names=label_mapping.keys()))
    fold += 1

print("\n--- Résultats finaux ---")
print(f"Scores F1 par fold : {f1_scores}")
print(f"Score F1 moyen : {np.mean(f1_scores):.4f}")

# Prédiction sur les données de test
!wget https://raw.githubusercontent.com/shael-nlp/classification-symp/refs/heads/main/data/test_data.csv
test_data = pd.read_csv('test_data.csv')

test_data['label_encoded'] = test_data['label_fr'].map(label_mapping)

test_sequences_desc = tokenizer.texts_to_sequences(test_data['description'])
test_sequences_simple = tokenizer.texts_to_sequences(test_data['simple'])
test_sequences_fautes = tokenizer.texts_to_sequences(test_data['fautes'])

X_test_desc = pad_sequences(test_sequences_desc, maxlen=max_length, padding='post')
X_test_simple = pad_sequences(test_sequences_simple, maxlen=max_length, padding='post')
X_test_fautes = pad_sequences(test_sequences_fautes, maxlen=max_length, padding='post')

test_sets = {
    'Description': (X_test_desc, test_data['label_encoded']),
    'Simple': (X_test_simple, test_data['label_encoded']),
    'Fautes': (X_test_fautes, test_data['label_encoded'])
}

results = []
final_model = build_model()
final_model.fit(X, y, epochs=5, batch_size=32, verbose=1)  # Entraîner sur toutes les données

for test_name, (X_test, y_test) in test_sets.items():
    y_test_pred = np.argmax(final_model.predict(X_test), axis=-1)
    f1 = f1_score(y_test, y_test_pred, average='macro')
    results.append({'Test Version': test_name, 'F1': f1})

results_df = pd.DataFrame(results)
print("\nRésultats comparatifs avec le modèle final :")
print(results_df)

plt.figure(figsize=(10, 5))
sns.barplot(data=results_df, x='Test Version', y='F1')

for index, row in results_df.iterrows():
    plt.text(
        x=index,
        y=row['F1'] + 0.02,
        s=f"{row['F1']:.2f}",
        ha='center',
        fontsize=10,
        color='black'
    )

plt.title("Performances des CNN")
plt.ylabel("Score F1")
plt.xlabel("Colonne")
plt.ylim(0, 1)
plt.show()

results_df.to_csv("test_result_CNN.csv", index=False)
print("Résultats enregistrés.")