# -*- coding: utf-8 -*-
"""Projet-apprentissage-auto-partie2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJjvVe1jds_r-YMwUfnndlS3tUS_femc

# Projet - Apprentissage automatique

- [Partie 1 - Analyse des données](https://colab.research.google.com/drive/1TCqrBM1zKQ1MCa9r-cG91Jc7WjS5Hl8X?usp=sharing)
- [Spécial - Division des données](https://colab.research.google.com/drive/1nj8v8rWsDm34sya57gXGBetxj_wQgUb7?usp=sharing)
- [Vous êtes ici]
- [Partie 3 - CNN](https://colab.research.google.com/drive/13NIe3ENacjGwOxr6ZYAuF7Xg5K_rpy2u?usp=sharing)
- [Partie 4 - BILSTM](https://colab.research.google.com/drive/1QA7sIiwOHSTdhzxJzh0D-HS1SRHa3SIm?usp=sharing)
- [Partie 5 - Transformers](https://colab.research.google.com/drive/1U-vjDYcGoGWQHiG-YZ8TWFFwi-uwp7aA?usp=sharing)
- [Partie 6 - Conclusion](https://colab.research.google.com/drive/1CInFVJpJoXfEVUUbGCXDJ4CACKKGF4N_?usp=sharing)

## Partie 2 : ML classique
Dans cette partie, nous testons les approches de classification automatique dites "classiques" ou statistiques.
"""

!pip install spacy
!python -m spacy download fr_core_news_sm

import warnings
warnings.filterwarnings('ignore')
import string
from sklearn import metrics
from sklearn import model_selection
from sklearn import set_config
from sklearn.dummy import DummyClassifier
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import make_pipeline
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import spacy
import fr_core_news_sm

set_config(display='diagram')

"""Les données d'entraînement ont déjà été préalablement divisées en un ratio de 80/20 %, les 20 % restants étant réservés au test final."""

!wget https://raw.githubusercontent.com/shael-nlp/classification-symp/refs/heads/main/data/train_data.csv

data = pd.read_csv('train_data.csv')

"""Nous partons sur une approche sans lemmatisation, mais la lemmatisation pourrait être employée plus tard"""

spacy_pipeline = fr_core_news_sm.load(disable=["parser", "ner", "lemmatizer"])
def split_into_tokens_wosw_spacy(text):
    doc = spacy_pipeline(text)
    return ' '.join([t.text for t in doc if not t.is_stop])

"""### 1. Apprentissage sur toutes les données
J'ai décidé d'entraîner directement les algorithmes d'apprentissage sur l'ensemble des données (Les trois colonnes en même temps), car, en théorie, cela multiplie les exemples et améliore l'apprentissage.

Cette approche nécessite de modifier le format des données, car si l'on fournit 3 phrases par label durant l'entrainement, le modèle devra toujours disposer de 3 phrases pour effectuer ses tâches de prédiction, ce qui est un inconvénient important.
"""

data_complete = pd.DataFrame({
    'text': pd.concat([data['description'], data['simple'], data['fautes']], ignore_index=True),
    'label': pd.concat([data['label_fr'], data['label_fr'], data['label_fr']], ignore_index=True)
})

print(data_complete.shape)  # Devrait montrer 608 * 3 = 1824 lignes
print(data_complete.head())

data_complete['tokenised_text'] = data_complete['text'].apply(split_into_tokens_wosw_spacy)

X = data_complete['tokenised_text']
y = data_complete['label']

def split_text(text) :
  return text.split(' ')

text_vectorizer = TfidfVectorizer(tokenizer=split_text,
                                  stop_words=list(string.punctuation),
                                  min_df=0.01)

models = [
    ('Baseline', DummyClassifier(strategy='most_frequent')),
    ('Multinomial NB', MultinomialNB()),
    ('CART', DecisionTreeClassifier()),
    ('Logistic Regression', LogisticRegression()),
    ('KNN', KNeighborsClassifier()),
    ('Random Forest', RandomForestClassifier()),
    ('LinearSVC', LinearSVC()),
]

scores = []
names = []
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=12)
trained_pipelines = {}

"""Ci-dessous: entrainement des modèles avec cross-validation"""

for name, model in models:
    names.append(name)
    model_pipeline = make_pipeline(text_vectorizer, model)
    y_pred = model_selection.cross_val_predict(model_pipeline, X, y, cv=kfold)
    print(f"Évaluation du modèle : {name}")
    print(classification_report(y, y_pred))
    f1 = metrics.f1_score(y, y_pred, average='macro')
    scores.append(f1)
    # Conservation des pipelines
    model_pipeline.fit(X, y)
    trained_pipelines[name] = model_pipeline

indices = np.arange(len(scores))
fig = plt.figure(figsize=(10, 6))
plt.barh(indices, scores, .5, label="Score F1", color='b')
plt.yticks(indices, names)
plt.xlabel('Score F1')
plt.title('Comparaison des modèles')
plt.legend()
plt.show()

"""Ci-dessous, la possibilité de tester les modèles avec des phrases individuelles: Ce n'est pas vraiment utile dans le cadre de la comparaison mais cela permet de m'assurer que tout fonctionne."""

user_input = "Je tousse très fort"
preprocessed_user_input = split_into_tokens_wosw_spacy(user_input)


print(f"Prédictions pour la phrase utilisateur : {user_input}")
for name, pipeline in trained_pipelines.items():
    predicted_label = pipeline.predict([preprocessed_user_input])
    print(f"Modèle : {name} -> Maladie prédite : {predicted_label[0]}")

"""On peut maintenant essayer le modèle sur les données de test:"""

!wget https://raw.githubusercontent.com/shael-nlp/classification-symp/refs/heads/main/data/test_data.csv

test_data = pd.read_csv('test_data.csv')
test_data['tokenised_description'] = test_data['description'].apply(split_into_tokens_wosw_spacy)
test_data['tokenised_simple'] = test_data['simple'].apply(split_into_tokens_wosw_spacy)
test_data['tokenised_fautes'] = test_data['fautes'].apply(split_into_tokens_wosw_spacy)

X_test_desc = test_data['tokenised_description']
y_test_desc = test_data['label_fr']

X_test_simple = test_data['tokenised_simple']
y_test_simple = test_data['label_fr']

X_test_fautes = test_data['tokenised_fautes']
y_test_fautes = test_data['label_fr']

test_sets = {
    'Description': (X_test_desc, y_test_desc),
    'Simple': (X_test_simple, y_test_simple),
    'Fautes': (X_test_fautes, y_test_fautes)
}

results = {
    'Model': [],
    'Dataset': [],
    'F1': [],
}

for test_name, (X_test, y_test) in test_sets.items():
    for name, pipeline in trained_pipelines.items():
        # Prédire sur les données de test
        y_test_pred = pipeline.predict(X_test)

        f1 = metrics.f1_score(y_test, y_test_pred, average='macro')

        results['Model'].append(name)
        results['Dataset'].append(test_name)
        results['F1'].append(f1)

results_df = pd.DataFrame(results)

print("\nRésultats comparatifs :")
print(results_df)

plt.figure(figsize=(12, 5))
ax = sns.barplot(
    data=results_df,
    x='Dataset',
    y='F1',
    hue='Model',
    palette='muted'
)

# Ajouter des valeurs numériques sur les barres
for container in ax.containers:
    ax.bar_label(container, fmt='%.2f', label_type='edge', fontsize=10, padding=3)

# Positionner la légende en dehors du graphique
plt.title("Comparaison des modèles (entrainés sur toutes les colonnes) sur les différentes entrées (Score F1)")
plt.ylabel("Score F1 (Macro)")
plt.xlabel("Colonne")
plt.legend(loc='upper left', bbox_to_anchor=(1, 1))  # Légende en dehors
plt.tight_layout()  # Ajuster automatiquement la mise en page
plt.show()

"""Il serait maintenant intéressant de comparer plusieurs approches d'apprentissage aux résultats ci-dessus.

### 2. Entrainement sur colonnes individuelles
Il serait intéressant de comparer si l’entraînement sur une colonne individuelle (comme « description ») donnerait de meilleurs résultats sur les données de test que les modèles précédents, entraînés sur l’ensemble des colonnes.
- Nous allons donc entraîner les modèles individuellement sur les trois colonnes, puis les comparer aux résultats précédents avec un test sur les données de test.
"""

data['tokenised_description'] = data['description'].apply(split_into_tokens_wosw_spacy)
data['tokenised_simple'] = data['simple'].apply(split_into_tokens_wosw_spacy)
data['tokenised_fautes'] = data['fautes'].apply(split_into_tokens_wosw_spacy)

X_desc = data['tokenised_description']
y_desc = data['label_fr']

X_simple = data['tokenised_simple']
y_simple = data['label_fr']

X_fautes = data['tokenised_fautes']
y_fautes = data['label_fr']

single_sets = {
    'Description': (X_desc, y_desc),
    'Simple': (X_simple, y_simple),
    'Fautes': (X_fautes, y_fautes)
}

for dataset_name, (X_set, y_set) in single_sets.items():
    print(f"\n--- Validation croisée pour le dataset : {dataset_name} ---")
    names = []
    scores = []
    trained_pipelines = {}

    for name, model in models:
        names.append(name)
        model_pipeline = make_pipeline(text_vectorizer, model)

        y_pred = model_selection.cross_val_predict(model_pipeline, X_set, y_set, cv=kfold)

        print(f"\nÉvaluation du modèle : {name} sur {dataset_name}")
        print(classification_report(y_set, y_pred))

        f1 = metrics.f1_score(y_set, y_pred, average='macro')
        scores.append(f1)

        model_pipeline.fit(X_set, y_set)
        trained_pipelines[name] = model_pipeline

single_results = {
    'Train Version': [],
    'Test Version': [],
    'Model': [],
    'F1': [],
}

# Test des modèles sur toutes les combinaisons
for train_version, (X_train, y_train) in single_sets.items():
    print(f"\n--- Modèles entraînés sur la version : {train_version} ---")

    for test_version, (X_test, y_test) in test_sets.items():
        print(f"\n>> Évaluation sur la version de test : {test_version}")

        for model_name, model in models:
            pipeline = make_pipeline(text_vectorizer, model)
            pipeline.fit(X_train, y_train)

            y_test_pred = pipeline.predict(X_test)

            f1 = metrics.f1_score(y_test, y_test_pred, average='macro')

            single_results['Train Version'].append(train_version)
            single_results['Test Version'].append(test_version)
            single_results['Model'].append(model_name)
            single_results['F1'].append(f1)

            print(f"Modèle : {model_name} - Score F1 : {f1:.4f}")


single_results_df = pd.DataFrame(single_results)

print("\n--- Résultats complets des 9 combinaisons ---")
print(single_results_df)

plt.figure(figsize=(18, 8))
sns.barplot(
    data=single_results_df,
    x='Test Version',
    y='F1',
    hue='Train Version',
    palette='coolwarm'
)
plt.title("Performances des modèles sur les jeux de test (F1 Macro)")
plt.ylabel("Score F1 (Macro)")
plt.xlabel("Version des données de test")
plt.legend(title="Version entraînée", loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()
plt.show()

"""Si on fait la moyenne ce ces modèles et qu'on les compare au résultats du modèle précédent, on observe que l'entrainement sur l'ensemble des trois type d'exemples a de meilleures performances:"""

all_results = single_results_df.copy()
all_results['Training Type'] = 'Individuel'
results_df['Train Version'] = 'Toutes'
results_df['Training Type'] = 'Combiné'

results_df_renamed = results_df.rename(columns={
    'Dataset': 'Test Version',
    'Model': 'Model',
    'F1': 'F1'
})

comparison_df = pd.concat([all_results, results_df_renamed], ignore_index=True)

plt.figure(figsize=(18, 8))
ax = sns.barplot(
    data=comparison_df,
    x='Test Version',
    y='F1',
    hue='Training Type',
    palette='coolwarm'
)

for container in ax.containers:
    for bar in container:
        bar_value = bar.get_height()
        bar_x = bar.get_x() + bar.get_width() / 2
        horizontal_offset = 0.08
        ax.text(bar_x + horizontal_offset, bar_value, f"{bar_value:.2f}",
                ha='center', va='bottom', fontsize=10)

plt.title("Comparaison des modèles (entraînement combiné vs individuel) sur différentes données de test")
plt.ylabel("Score F1 (Macro)")
plt.xlabel("Version des données de test")
plt.legend(title="Type d'entraînement", loc='upper left', bbox_to_anchor=(1, 1))
plt.tight_layout()
plt.show()

"""Enregistrement des fichiers pour effectuer une comparaison avec les autres modèles dans les parties suivantes"""

comparison_df.to_csv('test_result_ML.csv', index=False, encoding='utf-8')

print("Fichier enregistré.")