# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nj8v8rWsDm34sya57gXGBetxj_wQgUb7

Division des données

## Division des données:
les données de test seront utilisées pour la validation finale
"""

import pandas as pd
from sklearn.model_selection import train_test_split

!wget https://git.unistra.fr/dbernhard/ftaa_data/-/raw/main/final_symptom_dataset.csv

data = pd.read_csv('final_symptom_dataset.csv')

train_data, test_data = train_test_split(data, test_size=0.2, random_state=12)

print(f"Nombre d'exemples dans l'ensemble d'entraînement: {len(train_data)}")
print(f"Nombre d'exemples dans l'ensemble de test: {len(test_data)}")

train_data.to_csv("train_data.csv", index=False)
test_data.to_csv("test_data.csv", index=False)