# -*- coding: utf-8 -*-
"""Projet-apprentissage-auto-partie5-transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-vjDYcGoGWQHiG-YZ8TWFFwi-uwp7aA

# Projet - Apprentissage automatique

- [Partie 1 - Analyse](https://colab.research.google.com/drive/1TCqrBM1zKQ1MCa9r-cG91Jc7WjS5Hl8X?usp=sharing)
- [Spécial - Division des données](https://colab.research.google.com/drive/1nj8v8rWsDm34sya57gXGBetxj_wQgUb7?usp=sharing)
- [Partie 2 - ML Classique](https://colab.research.google.com/drive/1xJjvVe1jds_r-YMwUfnndlS3tUS_femc?usp=sharing)
- [Partie 3 - CNN](https://colab.research.google.com/drive/13NIe3ENacjGwOxr6ZYAuF7Xg5K_rpy2u?usp=sharing)
- [Partie 4 - BILSTM](https://colab.research.google.com/drive/1QA7sIiwOHSTdhzxJzh0D-HS1SRHa3SIm?usp=sharing)
- [Vous êtes ici]
- [Partie 6 - Conclusion](https://colab.research.google.com/drive/1CInFVJpJoXfEVUUbGCXDJ4CACKKGF4N_?usp=sharing)

# Partie 5 - Transformers
"""

!pip install transformers datasets evaluate

import pandas as pd
import numpy as np
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, DataCollatorWithPadding, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import evaluate

# Téléchargement des données d'entraînement
!wget https://raw.githubusercontent.com/shael-nlp/classification-symp/refs/heads/main/data/train_data.csv
data = pd.read_csv('train_data.csv')

data_complete = pd.DataFrame({
    'text': pd.concat([data['description'], data['simple'], data['fautes']], ignore_index=True),
    'label_fr': pd.concat([data['label_fr'], data['label_fr'], data['label_fr']], ignore_index=True)
})

label_fr_mapping = {label: idx for idx, label in enumerate(data_complete['label_fr'].unique())}
data_complete['label_fr_encoded'] = data_complete['label_fr'].map(label_fr_mapping)

# Séparation entraînement/validation
train_data, val_data = train_test_split(data_complete, test_size=0.2, stratify=data_complete['label_fr_encoded'], random_state=42)

# Conversion en Dataset Hugging Face
train_dataset = Dataset.from_pandas(train_data[['text', 'label_fr_encoded']])
val_dataset = Dataset.from_pandas(val_data[['text', 'label_fr_encoded']])

datasets = DatasetDict({
    'train': train_dataset.rename_column('label_fr_encoded', 'labels'),
    'validation': val_dataset.rename_column('label_fr_encoded', 'labels')
})

model_ckpt = "cmarkea/distilcamembert-base"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True, padding=True, max_length=128)

tokenized_datasets = datasets.map(preprocess_function, batched=True, remove_columns=["text"])

accuracy_metric = evaluate.load("accuracy")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_metric.compute(predictions=predictions, references=labels)['accuracy']
    f1 = f1_metric.compute(predictions=predictions, references=labels, average='macro')['f1']
    return {"accuracy": acc, "f1_macro": f1}

num_labels = len(label_fr_mapping)
model = AutoModelForSequenceClassification.from_pretrained(model_ckpt, num_labels=num_labels)

training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    logging_dir="./logs",
    report_to="none"
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Entraînement du modèle
trainer.train()

# Prédiction sur les données de test
!wget https://raw.githubusercontent.com/shael-nlp/classification-symp/refs/heads/main/data/test_data.csv
test_data = pd.read_csv('test_data.csv')

test_data['label_fr_encoded'] = test_data['label_fr'].map(label_fr_mapping)

inv_label_fr_mapping = {v: k for k, v in label_fr_mapping.items()}

test_f1_scores = []

for col in ['description', 'simple', 'fautes']:
    test_dataset_col = Dataset.from_pandas(
        test_data[[col, 'label_fr_encoded']].rename(columns={col: 'text', 'label_fr_encoded': 'labels'})
    )
    tokenized_test_dataset_col = test_dataset_col.map(preprocess_function, batched=True, remove_columns=["text"])

    col_predictions = trainer.predict(tokenized_test_dataset_col)
    f1_col = f1_score(test_data['label_fr_encoded'], np.argmax(col_predictions.predictions, axis=-1), average='macro')

    test_f1_scores.append({
        "Test Version": col,
        "F1": f1_col
    })

f1_scores_df = pd.DataFrame(test_f1_scores)

f1_scores_df.to_csv("test_result_transformers.csv", index=False)
print("Résultats enregistrés.")